req:  <ref *2> IncomingMessage {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: false,
    ended: true,
    endEmitted: true,
    reading: false,
    constructed: true,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: true,
    errored: null,
    closed: true,
    closeEmitted: true,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: true,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: true
  },
  _events: [Object: null prototype] { end: [Function: clearRequestTimeout] },
  _eventsCount: 1,
  _maxListeners: undefined,
  socket: <ref *1> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      timeout: [Function: socketOnTimeout],
      data: [Function: bound socketOnData],
      error: [Array],
      close: [Array],
      drain: [Function: bound socketOnDrain],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 8,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      httpAllowHalfOpen: false,
      timeout: 0,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      headersTimeout: 60000,
      requestTimeout: 0,
      _connectionKey: '6::::6543',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 73,
      [Symbol(kUniqueHeaders)]: null
    },
    _server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      httpAllowHalfOpen: false,
      timeout: 0,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      headersTimeout: 60000,
      requestTimeout: 0,
      _connectionKey: '6::::6543',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 73,
      [Symbol(kUniqueHeaders)]: null
    },
    parser: HTTPParser {
      '0': [Function: bound setRequestTimeout],
      '1': [Function: parserOnHeaders],
      '2': [Function: parserOnHeadersComplete],
      '3': [Function: parserOnBody],
      '4': [Function: parserOnMessageComplete],
      '5': [Function: bound onParserExecute],
      '6': [Function: bound onParserTimeout],
      _headers: [],
      _url: '',
      socket: [Circular *1],
      incoming: [Circular *2],
      outgoing: null,
      maxHeaderPairs: 2000,
      _consumed: true,
      onIncoming: [Function: bound parserOnIncoming],
      [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
    },
    on: [Function: socketListenerWrap],
    addListener: [Function: socketListenerWrap],
    prependListener: [Function: socketListenerWrap],
    setEncoding: [Function: socketSetEncoding],
    _paused: false,
    _httpMessage: ServerResponse {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      _closed: false,
      socket: [Circular *1],
      _header: null,
      _keepAliveTimeout: 5000,
      _onPendingData: [Function: bound updateOutgoingData],
      req: [Circular *2],
      _sent100: false,
      _expect_continue: false,
      locals: [Object: null prototype] {},
      _startAt: undefined,
      _startTime: undefined,
      writeHead: [Function: writeHead],
      __onFinished: [Function],
      flush: [Function: flush],
      write: [Function: write],
      end: [Function: end],
      on: [Function: on],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _peername: { address: '::1', family: 'IPv6', port: 60795 },
    timeout: 0,
    [Symbol(async_id_symbol)]: 87,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      _consumed: true,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 7649,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: false,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 95,
      [Symbol(triggerId)]: 91
    },
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kSetNoDelay)]: false,
    [Symbol(kSetKeepAlive)]: false,
    [Symbol(kSetKeepAliveInitialDelay)]: 0,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(RequestTimeout)]: undefined
  },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: true,
  rawHeaders: [
    'Host',
    'localhost:6543',
    'Connection',
    'keep-alive',
    'Content-Length',
    '22810',
    'sec-ch-ua',
    '"Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"',
    'Accept',
    'application/json, text/plain, */*',
    'Content-Type',
    'multipart/form-data; boundary=----WebKitFormBoundarycxtuLN1FoEO4vHxi',
    'sec-ch-ua-mobile',
    '?0',
    'Authorization',
    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Mzk3MTEyZS0xMmQ5LTQ5ZmMtYjViMS04YjBiMDllZDU0YzciLCJlbWFpbCI6ImRoaWV1QGdtYWlsLmNvbSIsInBob25lX251bWJlciI6IjAzNzU0MzU4OTIiLCJ
yb2xlIjoidXNlciIsImlhdCI6MTY4MzQ3OTYzMSwiZXhwIjoxNjgzNDgxNDMxLCJ0eXBlIjoiQWNjZXNzIn0.NyGZcb3jIuB-p8KjcALh4LGnQETp3zBVEWkSr-5_tQs',
    'User-Agent',
    'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
    'sec-ch-ua-platform',
    '"Windows"',
    'Origin',
    'http://localhost:3456',
    'Sec-Fetch-Site',
    'same-site',
    'Sec-Fetch-Mode',
    'cors',
    'Sec-Fetch-Dest',
    'empty',
    'Referer',
    'http://localhost:3456/',
    'Accept-Encoding',
    'gzip, deflate, br',
    'Accept-Language',
    'vi,fr-FR;q=0.9,fr;q=0.8,en-US;q=0.7,en;q=0.6'
  ],
  rawTrailers: [],
  aborted: false,
  upgrade: false,
  url: '/avatar',
  method: 'POST',
  statusCode: null,
  statusMessage: null,
  client: <ref *1> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      timeout: [Function: socketOnTimeout],
      data: [Function: bound socketOnData],
      error: [Array],
      close: [Array],
      drain: [Function: bound socketOnDrain],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 8,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      httpAllowHalfOpen: false,
      timeout: 0,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      headersTimeout: 60000,
      requestTimeout: 0,
      _connectionKey: '6::::6543',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 73,
      [Symbol(kUniqueHeaders)]: null
    },
    _server: Server {
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      noDelay: false,
      keepAlive: false,
      keepAliveInitialDelay: 0,
      httpAllowHalfOpen: false,
      timeout: 0,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      maxRequestsPerSocket: 0,
      headersTimeout: 60000,
      requestTimeout: 0,
      _connectionKey: '6::::6543',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 73,
      [Symbol(kUniqueHeaders)]: null
    },
    parser: HTTPParser {
      '0': [Function: bound setRequestTimeout],
      '1': [Function: parserOnHeaders],
      '2': [Function: parserOnHeadersComplete],
      '3': [Function: parserOnBody],
      '4': [Function: parserOnMessageComplete],
      '5': [Function: bound onParserExecute],
      '6': [Function: bound onParserTimeout],
      _headers: [],
      _url: '',
      socket: [Circular *1],
      incoming: [Circular *2],
      outgoing: null,
      maxHeaderPairs: 2000,
      _consumed: true,
      onIncoming: [Function: bound parserOnIncoming],
      [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
    },
    on: [Function: socketListenerWrap],
    addListener: [Function: socketListenerWrap],
    prependListener: [Function: socketListenerWrap],
    setEncoding: [Function: socketSetEncoding],
    _paused: false,
    _httpMessage: ServerResponse {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      _closed: false,
      socket: [Circular *1],
      _header: null,
      _keepAliveTimeout: 5000,
      _onPendingData: [Function: bound updateOutgoingData],
      req: [Circular *2],
      _sent100: false,
      _expect_continue: false,
      locals: [Object: null prototype] {},
      _startAt: undefined,
      _startTime: undefined,
      writeHead: [Function: writeHead],
      __onFinished: [Function],
      flush: [Function: flush],
      write: [Function: write],
      end: [Function: end],
      on: [Function: on],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _peername: { address: '::1', family: 'IPv6', port: 60795 },
    timeout: 0,
    [Symbol(async_id_symbol)]: 87,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      _consumed: true,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 7649,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: false,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 95,
      [Symbol(triggerId)]: 91
    },
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kSetNoDelay)]: false,
    [Symbol(kSetKeepAlive)]: false,
    [Symbol(kSetKeepAliveInitialDelay)]: 0,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(RequestTimeout)]: undefined
  },
  _consuming: true,
  _dumped: false,
  next: [Function: next],
  baseUrl: '/upload',
  originalUrl: '/upload/avatar',
  _parsedUrl: Url {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: null,
    query: null,
    pathname: '/avatar',
    path: '/avatar',
    href: '/avatar',
    _raw: '/avatar'
  },
  params: {},
  query: {},
  res: <ref *3> ServerResponse {
    _events: [Object: null prototype] {
      finish: [Array],
      end: [Function: onevent]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: false,
    _headerSent: false,
    _closed: false,
    socket: <ref *1> Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      setEncoding: [Function: socketSetEncoding],
      _paused: false,
      _httpMessage: [Circular *3],
      _peername: [Object],
      timeout: 0,
      [Symbol(async_id_symbol)]: 87,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 7649,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 95,
        [Symbol(triggerId)]: 91
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: null,
    _keepAliveTimeout: 5000,
    _onPendingData: [Function: bound updateOutgoingData],
    req: [Circular *2],
    _sent100: false,
    _expect_continue: false,
    locals: [Object: null prototype] {},
    _startAt: undefined,
    _startTime: undefined,
    writeHead: [Function: writeHead],
    __onFinished: [Function: listener] { queue: [Array] },
    flush: [Function: flush],
    write: [Function: write],
    end: [Function: end],
    on: [Function: on],
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'content-security-policy': [Array],
      'cross-origin-embedder-policy': [Array],
      'cross-origin-opener-policy': [Array],
      'cross-origin-resource-policy': [Array],
      'x-dns-prefetch-control': [Array],
      'x-frame-options': [Array],
      'strict-transport-security': [Array],
      'x-download-options': [Array],
      'x-content-type-options': [Array],
      'origin-agent-cluster': [Array],
      'x-permitted-cross-domain-policies': [Array],
      'referrer-policy': [Array],
      'x-xss-protection': [Array],
      'access-control-allow-origin': [Array],
      'access-control-allow-credentials': [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  _startAt: [ 142212, 459263000 ],
  _startTime: 2023-05-07T17:25:23.664Z,
  _remoteAddress: '::1',
  body: [Object: null prototype] {
    image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAIABJREFUeJzs3Xl8XXWd//HX99
wlO5SlrEWppLk3DRS0IIsF2UFFQLZxVPiB4jCCC4Kj4zzGBRWXGcQFZRQdFXBmVBgGFcdhkMEFBJQqi2nuTdMlbaFNF9qmSbPde76/P5KWLlnv9j3n3Pfz8fAhTXLPeXdJvp/7XT7HICKB9gwLE430zfbwD8oTO8hgZ1nMLIPdb+z/ZxnsvhbTYD
H1BtsAJMc+Fgf23eOSjUBij4+NAH17fGyLweYtZiswbDH9BrvdYPstZovBbrGYLWP/vdnH2xIjv95iNqzl0PVn8Otcef5ERKQUjOsAItVsKc2zgTl5YkdYzKsMdg4wBzjcYg4y2NnAbLcpC7bBYNdbzAZgDfCixawBumPkV1vMmhSdGx1nFKlaKg
BEyshCLEvqVT5es4d/lME2W8xRQDNwFFDnOKJrA0AXsAzospiuGP6yPF5XmswqA77jfCKRpQJApEQypA7zsPN9TJvBzreYNuA4oMF1tpAatpgug223mCUG254ntmQ+SzIG8q7DiYSdCgCRGXqGhYk6Blri5BZazEJgIfBaoN5xtGoxYjFLDXYxsN
hgF2+j6U/Hs3i762AiYaICQGQSFmIZ0vM9/BMt5iTg9UArEHccTXaXA5YAfwCe8vGebqVjiZYQRCamAkBkF0tp3sfHWwS8wWJOBo4HmhzHksL0An8EnjLYJyzm8TTZba5DiQSFCgCpahlSTR72RB9zNrCI0Xf4ex6Rk2jIW0zWw3/cYn5lsI/pFI
JUMxUAUlVWM6duG02LPPxzgHOAY9H3QbXyLeY5g33Ewz6SYPjxuawcdB1KpFL0g08iL0vLsRZznsWcY7CLgFrXmSSQBoDfWcwjwMOtZF5wHUiknFQASOSs4MjaEZKLfMxbgYuBV7nOJKHUbbAP+3gP1TL4iGYHJGpUAEgkdJA+wGAvAi4EzkZn76
W0+i3mf4Gf+cR+1kb7y64DiRRLBYCEVpaWA4E3A5dbzHlo855URh54CrjPx/vJfDrWug4kUggVABIqL3D0wXFyVxjsFcApgOc6k1S1vMU84eH/xMP/yTy6NrgOJDJdKgAk8FYzp66fhgsM9iq905cAywNPWcw9Bvsf6jkgQacCQALpMU6PH8K68w
32SuCt6KE5Ei7bLeZnMfI/nMfS/9GzCySIVABIoGRIpSzmrw32GrR7X6JhLXAf8K9pss+7DiOygwoAcS5Dqslg324x1wAnu84jUkZPAN/PE/9xG+19rsNIdVMBIM5kaUlbzNXA3wD7OY4jUknbDPY/gDtTdD7nOoxUJxUAUlHttCVj5C6ymL8x2L
Nd5xEJgMUWc1cjffcewZoB12GkeqgAkIrIkDoMuJ7Rd/uzHccRCaL1wF0+3p3qLSCVoAJAymoJra+Lkb/OYq5CPfhFpmMY+KnFfKWVzJOuw0h0qQCQkrPgZUldAnyY0WY9IlKYxy3mK2kyDxrwXYeRaFEBICXTTlsyzsjbLebjQNp1HpEIWQ58vY
ahb+uhRFIqKgCkaBlSTcC7gb8DDnccRySyDLbHx/tWLYNfncvKLa7zSLipAJCCtdO2f4zch4EPAPu6ziNSRbZYzNdHSHx1AS9sdh1GwkkFgMxYB+kDgA8Y7IeAWa7ziFSxPuCbeeL/pEcUy0ypAJBpy9JyoI/3foO9Eb3jFwmSPuB7IyQ+fwx/6X
EdRsJBBYBMqZ22xhi5G4CPo4FfJMj6gG8mGPnCUSzf6jqMBJsKAJlQO21Jj/zVHv5nLOZg13lEZNo2Af9cw9DXdGpAJqICQPbyGKfHD+Olayzmk8Ac13lEpGCrgFtSZO/WI4llTyoAZDedtJztY24HjnGdRURKJmOwN6Xo/KXrIBIcKgAEgKU0z8
8T+2fgza6ziEh5GOxDHv6N8+ha5jqLuKcCoMplaTkc+NxYr37PdR4RKbsh4Gsx8rfOo6vXdRhxRwVAlXqGhYlG+q4HPgs0uc4jIhW3Cfhsiuw3tD+gOqkAqEJZWs7y8b5usPNdZxERtyzmzzHyN7aw9Leus0hlqQCoIktpPipP7AvA5a6ziEiwGO
xDFvPBNNkVrrNIZagAqALPsDDRQP/fGewngFrXeUQksAaAT6/l0NvP4Nc512GkvFQARFwn847z8b4LLHSdRURC43mDvTZF5x9dB5HyUQEQUauZU9dPw6eAjwAx13lEJHRywJ1D1PzDsTzf7zqMlJ4KgAjqZN5pPt53gBbXWUQk9JZ72Ota6PyV6y
BSWioAImQFR84aJvkli3kv+rsVkdK6z2Le10pmk+sgUhoaJCKig/RbDfZfgMNdZxGRaDLYHuCjKTrvcZ1FiqcCIOTGOvl9y2IucJ1FRKrGT328982nY63rIFI4FQAhlqXlbRbzHeAA11lEpOpsMdj3pej8kesgUhgVACE0tsP/i8AHXWcRkap3b5
749W2097kOIjOjAiBkMqSOB/4N7fAXkeBYYTHvbCXzpOsgMn16+ltIWDAZUh8CnkCDv4gEy1yD/W0H6U9b9R0JDc0AhEA7ba+KkbsHeKPrLCIiU3gSeKeeKRB8mgEIuAypy2Lk/owGfxEJh5OBP2dIvdN1EJmcZgACainN++SJfQO40nUWEZFCGO
wPciQ+oA2CwaQCIIAypFIW84DBznedRUSkSJ15Ype0saTddRDZnZYAAiZD6kLgaQ3+IhIRLTHyT2ZIXeY6iOxOBUBAWIhlSH0ReBDY13UeEZESagJ+kiH1tcc4Pe46jIzSEkAAZGk5EPh3iznHdRYRkTL7zQiJvzqGv/S4DlLtVAA4toTW13n4/w
kc6TqLiEiFrPHwL2th6dOug1QzLQE4lKXlKg//cTT4i0h1mePj/SZLy3tdB6lmmgFwYCnNNTnidxis/vGLSLW7t4H+645gzYDrINVGBUCFZUgdxuhGvxNcZxERCQKLedondnEb7etcZ6kmKgAqaAmtR3v4vwBe5TqLiEjAvOjhX9DC0mddB6kW2g
NQIZ20nD223q/BX0Rkb4f7eL/N0vIm10GqhQqACsiQusbH/Dc63y8iMpkmi/lZB+nrXAepBioAysiC6SD9aeB7QMJxHBGRMIgb7LcypL5mtUxdVvrDLZOlNNfkif0roCdiiYgU5r4ahq6ay8pB10GiSAVAGbTTtn+M3APoEb4iIsX6vcFelKJzo+
sgUaMCoMQ6aXmNj/kFkHadRUQkCgy2K0/szfPpWOo6S5SoACihLC2vt5iHgNmus4iIRInB9vh4b2kls9h1lqjQJsAS6SB9usU8ggZ/EZGSs5iDDfbXGVJnuM4SFSoASqCD9FsN9pfAPq6ziIhEWCPwUAfpc10HiQIVAEXKkHqXwT4A1LrOIiJSBe
oN9udZWt7mOkjYqQAoQpaWDwP3AHHXWUREqkjSYn6cpeWvXAcJMxUABcqQ+juLuR1tpBQRcSFhMf+WIfUe10HCSgVAATKkPgb8k+scIiJVLgZ8J0PqRtdBwkgFwAyNtfb9ouscIiICjM7CfiVLy6dcBwkbTV/PQIbUZ4F/dJ1DRETG9aU02b93HS
IsNAMwTVlabkWDv4hIkH0sQ+ozrkOEhWYApkHv/EVEwsNgP56iU0u1U1ABMIUsLZ+0mFtc5xARkekz2JtTdN7uOkeQqQCYRAfpmw32Ntc5RERkxqzBXpei8zuugwSVCoAJjB0r+YrrHCIiUrC8wb4zReePXQcJIhUA48jScqXF3I3+fEREwm7EYi
5tJfNz10GCRgPcHjKkLgLuR+19RUSiYthgL07R+UvXQYJEBcAuMqTOBH6BHuwjIhI12z38N7Ww9LeugwSFCoAxWVpebzGPMvq4SRERiZ6tFnNWK5nFroMEgQoAIENqLvAUcJDrLCIiUlYb88RPbqO9y3UQ16q+E2A7bfsDv0SDv4hINTgwRu7nz3
PMfq6DuFbVBUA7bckYufuAlOssIiJSMekEIw8upbnGdRCXqrYAsGBi5L4LnOk6i4iIVJbBnpYj/gNbxUvhVVsAdNLyOeBK1zlERMQNg317hnTVPka4KiufDKl3A//qOoeIiDhnLeaaVjJ3uw5SaVVXAHSQPt1gHwaSrrOIiEggjHjYN7fQ+SvXQS
qpqgqApTTPzxN7ApjlOouIiARKr8UsaiXzgusglVI1BcASWg/18J8CXuU6i4iIBNLKsR4B61wHqYSq2AS4giNrPfyfosFfREQmdmSckf+qluOBVVEADFHzDeAE1zlERCTYLOakPLGvuc5RCZEvADpI/w3wHtc5REQkNK7LkIr8uBHpPQBjD/j5LV
AV0zkiIlIyg8CpabLPuA5SLpEtADpIH2CwzwBHus4iIiKhtMpgF6bo3Og6SDlEcgnAQsxg/x0N/iIiUrhXWcyPLMRcBymHSBYAWVJfBM51nUNERELvrE5aPuM6RDlEbgkgS8vFFvMAEfy9iYiIExa4Ik32ftdBSilSg2SGVAr4A7CP6ywiIhIp22
LkT5pH1xLXQUolMksAS2neB/gpGvxFRKT0mnLE72unrdF1kFKJTAGQJ/YNIOU6h4iIRJPBzo+R+6rrHKUSiSWADKnLgPtc5xARkegz2Len6Pyx6xzFCn0BsJTmOXlizwH7u84iIiJVYUue+LFttK9yHaQYoV4CsODlid2DBn8REamcWR75e8PeHy
DUBUCW1MeBM1znEBGR6mKwp2VJ3ew6RzFCuwTQQXqhwf4eSLrOIiIiVWnEYBel6PyD6yCFCOUMwHMsaDDYf0ODv4iIuJMA/i2sRwNDWQDUMPQ1dORPREQcs5jmGLl/dp2jEKFbAsjS8raxVr8iIiJBcXGa7E9dh5iJUBUAWVoOt5jngANcZxEREd
nFRh9vwXw61roOMl2hWgKwmG+iwV9ERILnQIP9jusQMxGaAiBLy9uBi1znEBERGY/BvqWD9Dtc55iuUCwBtNO2f5yRJRZzsOssIiIik9g0QqLtGP7S4zrIVEIxAxBn5HYN/iIiEgIHJBj5tusQ0xH4GYAMqTOARwlBVhERkTGXp8ne7zrEZAI9qD
7DwvpG+p4HjnKdRUREZLoMtmeImtYFvLDZdZaJBHoJoIH+z6LBX0REQsZiDk4y/HnXOSYT2BmALC0nWMyThPxpSyIiUrV8izm1lczvXQcZTyBnAB7j9LiP9200+IuISHh5BvvtZ1iYcB1kPIEsAA5h3UcN9rWuc4iIiBTp6Eb6bnIdYjyBWwJYSv
NReWJ/AWpdZxERESmB7T7e/Pl0dLsOsqvAzQDkiX0FDf4iIhId9R7+ba5D7ClQMwAdpM812Idd5xARESk1izm/lUxgxrjAFADttCVj5J4HUq6ziIiIlEFHH43HHs/iEddBIEBLAB75m9HgLyIi0dXaxLYPuA6xQyBmALK0HG4xGaDRdRYREZEy6h
0h0RKEhwUFZQbgVjT4i4hI9O2TZPgzrkNAAGYAsrQcazF/IjjFiIiISDnlLea1rWRecBnC+aDr490WhBwiIiIVEjPYr7oO4XTg7SB9gcGe7TKDiIiIA2d2kD7PZQBnBcBjnB432H9ydX+RamdqDKbG+SqgSNUy2Nusw2feOCsADmHdu4FWV/cXqX
YNi2ppeIOaboo4dHSG9JWubu6kAFjBkbUG+48u7i0io5rOq6PxvHrXMUSqmsF+einNNS7u7aQAGKT2/cARLu4tImDi0HBGHU1n1WISWgYQcejVeWLXubhxxQuADKkmg/27St9XRF5Rf0otsX09vH086k9y8uZDRF7xjxlSTZW+qYsZgI8CBzm4r4
iMaTqvbtz/FhEnZgMfqvRNKzr3l6XlQItZDlS80hGRMTFD8+OHEjtgdPNxfrPPslNexOYd5xKpbluHSc5dwAubK3XDis4AWMxH0OAv4lT9Ccmdgz9AbD+PuuO1DCDi2L4JRm6s5A0rVgB0kD4AuL5S9xOR8Y035a/TACLuGeyNz3PMfpW6X8UKAA
//ZvTuX8Qtz9B4zt6DfdN59eDpNICIY/skGKnYXoCKFADttO1vMe+vxL1EZGJ1xyWJH7R347H4bI+64xIOEonIrio5C1CRAiBG7ib07l/Eucl2/DdpGUAkCPatYeiDlbhR2QuApTTvA9xQ7vuIyNQaz5m4AGg8ty4ADwgXEYv5UDttjeW+T9kLAB
/vemBWue8jIpOrPTpJYk58ws8nDo9T25asYCIRmcB+Hvlryn2TshYAS2musZiKTGWIyOSm0/BHpwFEgsFgP/wYp09csZdAWQuAHPGrgUPLeQ8RmZ7Gc6ce3NUVUCQw5h7K2reV8wZlKwAsxAz25nJdX0SmryaVIDl36jcTySPj1LToNIBIQJT1uT
llKwCypN4GzCvX9UVk+mbyzl6zACKBcUKWlkXlung5lwBuKuO1RWQGGs9rmMHXah+ASFBYTNlm0stSAHSQXgicXI5ri8jMJI+MUzNv+nuJaloSJF+jZQCRgLiok3mt5bhwWQoAg9W7f5GAaHrTzN/RN52rZQCRgDA+XllO05W8AMiQOgy4rNTXFZ
HCFLKmr2UAkUC5+gWOPrjUFy15AWCwNwDqJiISAInD49S0zvzbsbYtQeKIsh5BFpHpq00y/LelvmhJC4Cxxj/vLeU1RaRwTecX3t63aZK2wSJSWRZz/VKaa0p5zZIWAHlilwOzS3lNESlcMVP5WgYQCZSDcsQvKeUFS70E8L4SX09EChQ/OEbdsY
WvxtUdlyR+qJYBRAKkpMsAJSsAMqQWAKeU6noiUpym84p8up+BprNrS5ZHRIpjsKctofXoUl2vlDMAevcvEiCl6OinZQCRYPHwS7bPriQFwNhzi99RimuJSPHiB3rUva74/UL1xyeJzy77U8NFZPr+33MsmH5rz0mU5Ds7zshfA/uU4loiUrzGs+
sgVsz8/xjP0HimTgOIBMi+SYYvL8WFSlXav7tE1xGREphJ7/+pr6VlAJGAuaYUFym6AMiQSlnMiaUIIyLFi+3rUX9i6Y4L159US2xfLQOIBIXBntpOW3Ox1ynFd/V7KG6vsYiUUOPZdZgSnt4zcWg8S8sAIgFiYuSuLvYiRRUAj3F6HHhXsSFEpH
RKsft/T1oGEAmcqy3EirlAUQXAIax7E3BoMdcQkdLxGgz1J5f+7H7DG2rwGrUMIBIgh2dIn13MBYr6jjbYK4t5vYiUVuNZdZia0q/ImaSh8Qw1BRIJkmLH4IILgAypJuCCYm4uIqVVjun/HbQMIBI4F4/14SlIwQWAxVwCaGeQSEB4dYb6ReX7lm
w4tRavTvt9RQKkwSP/1kJfXHABYLDq/CcSIA1vLO8A7dUZGk7TMoBIkBjsXxf62oIKgC6OOgg4s9CbikjpNVVgil7LACKBc34H6QMKeWFBBUCO+NsBPSdUJCBM0tDwxvK/O288ozybDEWkYAmDLag1cKFLAFcU+DoRKYOGU2srckzPazA0vEHLAC
IBU5kCoJ22Q4CTC7mZiJRHOXf/70nLACKB88axpfkZmXEBEGfkkkJeJyLlYeLQcEblCoCms2oxCS0DiARILE/swpm+aMYDucVcOtPXiEj51J9c2Yf1ePuU9mFDIlK8QsbmGf3UGNtpeNpMbyIi5VPJ6f8dtAwgEjhnPc8x+83kBTMqAAz2QrT7Xy
Q4YsbJk/qazq3DFPUYEhEpsUQNQzPqzjvTecOLZ/j1IlJG9SckiR1Q+ZE4tp9H3fFaBhAJEouZ0T6AaRcAS2muQc1/RALFxfT/DloGEAmc88fG6mmZdgHg450FFPzQAREpMQONZ7kbhJvOqQNPpwFEAqTR4p063S+edgFgMXryn0iA1L02SfwQdw
vx8YNj1B2bcHZ/Edmbj3nLdL92JnsA3lxAFhEpk0r0/p+KlgFEAmfa+wCmVQBkSC0AXl1wHBEpucZz3D+Nu+m8OtAqgEiQvCZLS3o6XzjdGYDziwgjIiVWe3SSxBz3J3ITh8epbUu6jiEiu7CYaY3Z0yoALOac4uKISCm53P2/Jy0DiATOtMbsKQ
uAFRxZa7BvKD6PiJRK47nBGXSDVIyICABvnM5xwCkLgEFqTwP0HS4SEDUtCZJz3U//75A8Mk5Ni04DiARIQ474lE/tnbIAMFhN/4sESBDfcQcxk0g18/CnHLunswdABYBIgDSe3+A6wl60D0AkWKazd2/SAqCdtv2BY0qWSESKkjwyTs284Ez/71
DTkiD5Gi0DiATIwhUcOWuyL5i0AIgzctpUXyMildN0fnDfaTedU+s6goi8whshMekG/kkHdx/vtNLmEZFiBHmqPcjZRKrRVGP4pAWAwb6xtHFEpFCJw+PUzg/uNHvt0UkSRwRveUKkWlnMpGP4hAXAUpr3AY4teSIRKUjT+cFvu9sUgPbEIjLKYB
dmSDVN9PkJCwAfbxHg7lFjIrKbMEyxhyGjSBWJ+3gnTfTJyZYAFpUhjIgUYPTRu8HvuV93XJL4oVoGEAkKD//UiT83AYuZsGoQkcpqOjf40/8AGGg6S6cBRALkxIk+MW4BYEc/vrBscURkRsI0tR6mrCJV4EQ7wVg/7gezpI4G9ilrJBGZlviBHv
ULgz/9v0P9CUnis9U+RCQg9u2iOT3eJ8b9LjXYCacMRKSyGs+ug1gY5v/HeIbGM3UaQCQo8sTGXdKfYAnAqAAQCYjG84LX+38qWgYQCY6J3tRPNE/3+jJmEZFp8vbxqH99eKb/d6g/qZbYvloGEAmCid7U7/UduoIja4HWsicSkSk1nV2HSYRo+n
+MiUPjmToNIBIQ88fG9t3sVQAMk1wA6CCvSACEeSo9zNlFIiYxQN38PT+4VwHg4722MnlEZDJeg6HhlBrXMQrWsKgWr1HLACJB4OHvNbbv9d1psCoARAKg8cw6TE34pv93MElD4+laBhAJAouZugAAXleBLCIyhShMoUfh9yASBeO9ud+tALCjD/
85umKJRGRcXp2h4dTwv3tuOK0Wry68sxgiEbJgz46Au/0iQ/ooQB08RByLysAZlUJGJAIas6RevesH9qgG/LbK5hGR8URp6jxKvxeRMLOY3cb4PZYAzF7HBESksqK2eS7smxlFosJgdxvj99wEqAJAxLGoHZ8L+3FGkahQASAScFGcMo/i70kkbP
ac5fde+QQekKp4IhHZKaotdMPa0lgkYlot7PxG3FkAjO0O1AkAEYfqT47mQ3S8fTzqT9QygIhjjV00H77jFzt7/vt4zR6+m0gSCo1n1BI/KOY6RqQ1nhvdqfL9rmkicbj+/ZRTbn2evscGXceQAMsRbwbWwC4FgIff7CyRhMLAs8Mc8oX9aTxTE0
Uycw2n1qonQBn1PzHEuo9udB1DAm5srP/16H+PMdijXAWScMhv9nnxfRvp+cTL+APWdRwRAeywZcNtW1nzng3kNmgWVybn4+0c63fZBGg0AyBTs7Dlx/2sumwdQ50jrtOIVLXhFTm6r1jPy3f1gq+iXKZmsDvHem+8D4pMZWhpju7Leth8T5/rKC
JVqffBfrrfto6hJcOuo0i47BzrDYAFkyXVB0R3B5KUTdO5dRx86/6R3L0uEjR+n0/PpzbT+/PtrqNIOG1Lk90HxgqApTTPzhNb7zaThFnisBiHfvkA6hbqqJdIuQw+P8xLN21iZFXOdRQJsWGS+y/ghc0ewAiJI1wHknAbeSnP6netZ9MdWyGvtU
iRkrKw+Z4+Vr29R4O/FC3J8BEwtgfAw1cBIEWzedh4Ry+rr95ArifvOo5IJOQ2+qy5dgPrP7cZq7FfSmDHmO8BWIwKACmZ7U8PsfLCdfQ9OuA6ikio9T8+SPeFa+n/nZr7SOn4eK+CsQLAYFUASEnt6Bmw9qPqGSAyU3bIsv7WLaNn+zfqbL+U1o
4xf8e27TkOs0iE9T7YT/elPeoZIDJNw8tH6L5iPZvv3gaqnaUMdsz67ygADnOYRSJuuGuE7kvVM0'... 12674 more characters
  },
  secret: undefined,
  cookies: [Object: null prototype] {},
  signedCookies: [Object: null prototype] {},
  logIn: [Function (anonymous)],
  login: [Function (anonymous)],
  logOut: [Function (anonymous)],
  logout: [Function (anonymous)],
  isAuthenticated: [Function (anonymous)],
  isUnauthenticated: [Function (anonymous)],
  _sessionManager: SessionManager {
    _key: 'passport',
    _serializeUser: [Function: bound ]
  },
  _passport: {
    instance: Authenticator {
      _key: 'passport',
      _strategies: [Object],
      _serializers: [],
      _deserializers: [],
      _infoTransformers: [],
      _framework: [Object],
      _sm: [SessionManager],
      Authenticator: [Function: Authenticator],
      Passport: [Function: Authenticator],
      Strategy: [Function],
      strategies: [Object],
      _userProperty: 'user'
    }
  },
  route: Route {
    path: '/avatar',
    stack: [ [Layer], [Layer] ],
    methods: { post: true }
  },
  [Symbol(kCapture)]: false,
  [Symbol(kHeaders)]: {
    host: 'localhost:6543',
    connection: 'keep-alive',
    'content-length': '22810',
    'sec-ch-ua': '"Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"',
    accept: 'application/json, text/plain, */*',
    'content-type': 'multipart/form-data; boundary=----WebKitFormBoundarycxtuLN1FoEO4vHxi',
    'sec-ch-ua-mobile': '?0',
    authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Mzk3MTEyZS0xMmQ5LTQ5ZmMtYjViMS04YjBiMDllZDU0YzciLCJlbWFpbCI6ImRoaWV1QGdtYWlsLmNvbSIsInBob25lX251bWJlciI6IjAz
NzU0MzU4OTIiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4MzQ3OTYzMSwiZXhwIjoxNjgzNDgxNDMxLCJ0eXBlIjoiQWNjZXNzIn0.NyGZcb3jIuB-p8KjcALh4LGnQETp3zBVEWkSr-5_tQs',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
    'sec-ch-ua-platform': '"Windows"',
    origin: 'http://localhost:3456',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    referer: 'http://localhost:3456/',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'vi,fr-FR;q=0.9,fr;q=0.8,en-US;q=0.7,en;q=0.6'
  },
  [Symbol(kHeadersCount)]: 34,
  [Symbol(kTrailers)]: null,
  [Symbol(kTrailersCount)]: 0,
  [Symbol(RequestTimeout)]: undefined
}
POST /upload/avatar 400 66.973 ms - 42


