const ACCESS_TOKEN = "ACCESS_TOKEN";
const REFRESH_TOKEN = "REFRESH_TOKEN";
const ACCESS_TOKEN_EXP = "ACCESS_TOKEN_EXP";
const REFRESH_TOKEN_EXP = "REFRESH_TOKEN_EXP";

const COOKIES = {
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  ACCESS_TOKEN_EXP,
  REFRESH_TOKEN_EXP
};

export default { COOKIES };
